name: feedback_github
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app and upload it as an issue to GitLab
version: 3.0.0
homepage: https://github.com/defuncart/feedback_github
repository: https://github.com/defuncart/feedback_github
issue_tracker: https://github.com/defuncart/feedback_github/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  feedback: ^3.0.0
  http: ^1.0.0
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
